### ISSUE TITLE
More Information 

### ISSUE THREAD

**Issue by elarib** [kaoskeya/blood-donation#1]
Hi !
 Can you give us more information about this project ? What Framework is built with ?

**Comment by kaoskeya** [comment]
Hey,

This was built using Meteor (https://www.meteor.com/). I wrote it over a few hours as a few friends were doing a blood donation drive and wanted to collect information.

Kinda does the job, let me know if you will be using it, I can rewrite parts of it to be more efficient and easier to deploy and push it here.
